import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ThemeProvider } from "@/contexts/ThemeContext"; // Import ThemeProvider

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col" style={{ backgroundColor: 'var(--aura-bg)', color: 'var(--aura-text)' }}>
          <ThemeProvider> {/* Wrap children with ThemeProvider */}
            <main className="grow">{children}</main>
            <footer className="text-center text-gray-500 p-6 border-t">
              Built with Aura
            </footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
